name: Build Electron App
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
          

    - name: Build Electron App
      uses: samuelmeuli/action-electron-builder@v1.6.0
      with:
        args: |
          --linux deb tar.xz
          --windows nsis
          --macos dmg zip
